services:
  stats-server:
      build: ./stats/stats-server
      image: ewm_stats:latest
      container_name: ewm_stats_container
      ports:
        - "9090:9090"
      depends_on:
        - ewm-db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db

  ewm-db:
    image: postgres:16.1
    container_name: postgres
    ports:
        - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    volumes:
      - /var/lib/postgresql/data

  ewm-service:
      build: ./main
      image: ewm_main:latest
      container_name: ewm_main_container
      ports:
        - "8080:8080"