services:
  stats-server:
    ports:
      - "9090:9090"
    container_name: stats-container
    build:
      context: ./stats/stats-server

  stats-db:
    image: postgres:17-alpine
    container_name: stats-db-container
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/stats:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    ports:
      - "8081:8081"
    container_name: main-service-container
    build:
      context: ./main

  ewm-db:
    image: postgres:17-alpine
    container_name: main-db
    ports:
      - "5431:5431"
    volumes:
      - ./volumes/ewm:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10