server.port=9090

  # ????????? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-stats
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

  # JPA/Hibernate
management.endpoints.web.base-path=/actuator
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO
logging.level.ru.practicum.shareit=TRACE