server.port: 9090

spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.format_sql: true
spring.sql.init.mode: always

spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:file:./db/ewm_stats
  username: user
  password: user